expiry_days: 14
tax_percentage: 5
per_page: 5
minimum_bounty: 50
allow_locate: true
locate_cost: 5
messages:
    help:
        - "Bounties Help"
        - "-------------"
        - "/bounty help - This screen"
        - "/bounty add <player> <amount> - Creates or adds to the bounty on <player>. The server takes a percentage of all bounties."
        - "/bounty mine - Show details about any current bounty on your head."
        - "/bounty locate <player> - if there is an open bounty on <player> tells you how far away they are."
        - "/bounty cancel <player> - cancels an open bounty on <player>. This can only be done by the creator, and no money will be refunded."
        - "/bounty list - list all open bounties (newest first by default)"
        - "/bounty list mine - shows all current and historical bounties placed on you."
        - "/bounty list placed - shows all current and historical bounties placed by you."
        - "/bounty list newest - shows all open bounties ordered by creation time."
        - "/bounty list oldest - shows all open bounties ordered by creation time ascending."
        - "/bounty list highest - shows all open bounties ordered by total value."
        - "[Note: all list commands accept an optional page number]"
    usage: "Usage: /bounty [add|list|cancel|locate|mine|help] [options..]"
    add_usage: "Usage: add <targetName> <amount>"
    cancel_usage: "cancel <targetName>"
    list_usage: "Usage: list [mine|newest|oldest|highest|placed] [page]"
    locate_usage: "Usage: locate <playerName>"
    locate_disabled: "The 'locate' command has been disabled."
    list_head_mine: "Bounties Placed Against You:"
    list_head_newest: "Newest Bounties:"
    list_head_oldest: "Bounties Nearing Expiry:"
    list_head_highest: "Highest Bounties:"
    list_head_placed: "Bounties Placed By You:"
    login_warning: "§c{ added_by } §fhas placed a bounty on your head! see /bounty mine for details."
    list_item: "§7{number}§f. §c{target}§f - §c{total}§f [§7by: §c{ added_by }§f] §7expires: { expires }"
    no_player_match: "No matching player found for name '{ target }'."
    multiple_player_match: "More than 1 player matches '{ target }'."
    player_offline: "§c{ target } §fis not online."
    updated_bounty: "§c{ added_by }§f upped the bounty on §c{ target }§f to §c{ total }§f."
    new_bounty: "§c{ added_by } §fis offering a bounty of §c{ total } §ffor the death of §c{ target }§f."
    cancelled_bounty: "§c{ player }§f has called off the bounty on §c{ target }§f."
    claimed_bounty: "§c{ claimed_by }§f claimed the bounty on §c{ target }§f earing §c{ total }§f!"
    next_page: "Type: '/bounty list { type } { page }' for more results."
    minimum_bounty: "A minimum bounty of §c{ min }§f is required."
    insufficient_funds: "You do not have §c{ amount }§f." 
    locate: "§c{ target }§f is { distance }m away."
    no_results: "No Bounties."
    config_reloaded: "Bounties configuration reloaded."
    no_bounty: "There is no bounty on §c{ target }§f."
    my_bounty: "There is a bounty of §c{ total }§f on your head!  It was started by §c{ added_by }§f and §c{ num_contributors }§f have contributed to it.  The bounty expires { expires }."